import {readFileSync,writeFileSync} from 'node:fs';
const labels={title:'Titolo',emphasis:'Parole in rosso',subtitle:'Sottotitolo',image:'Foto di copertina',imageAlt:'Descrizione della foto',video:'Video di copertina',buttonLabel:'Testo pulsante',buttonHref:'Destinazione pulsante',eyebrow:'Sopratitolo',bottom:'Testo sotto la copertina',name:'Nome',phone:'Telefono',email:'Email',city:'Località',domain:'Dominio',description:'Descrizione',legalName:'Titolare',legalAddress:'Indirizzo del titolare',vat:'Partita IVA',contacts:'Contatti',items:'Elementi',icon:'Icona',area:'Comune e provincia',lat:'Latitudine',lng:'Longitudine',source:'Fonte coordinate',note:'Nota',intro:'Introduzione',welcomeParagraphs:'Paragrafi di presentazione'};
const field=(name,value)=>{const result={name,label:labels[name]||name.replace(/^(welcome|courses|news|documents|contact|gallery)/,v=>({welcome:'Presentazione — ',courses:'Corsi — ',news:'Notizie — ',documents:'Documenti — ',contact:'Contatti — ',gallery:'Gallerie — '})[v]).replace(/Eyebrow/,'Sopratitolo').replace(/Title/,'Titolo').replace(/Emphasis/,'Parole in rosso').replace(/Intro/,'Introduzione').replace(/Empty/,'Testo in assenza di contenuti').replace(/Note/,'Nota').replace('quoteEmphasis','Citazione — Seconda frase').replace('quote','Citazione').replace('updated','Ultimo aggiornamento').replace('CitazioneParole in rosso','Citazione — Seconda frase'),widget:'string'};if(Array.isArray(value)){result.widget='list';if(typeof value[0]==='object')result.fields=Object.entries(value[0]).map(([k,v])=>field(k,v));else result.field={name:'text',label:'Testo',widget:'text'};}else if(typeof value==='number'){result.widget='number';result.value_type='float';}else if(name==='image'||name==='video'){result.widget='r2-file';result.kind=name==='video'?'video':'image';result.required=false;}else if(/Paragraph|Intro|subtitle|description|note/i.test(name))result.widget='text';return result;};
const settings=['home','site','courses','locations','privacy'].map(name=>({name,label:({home:'Homepage',site:'Contatti e dati del sito',courses:'Corsi',locations:'Sedi e mappa',privacy:'Privacy Policy'})[name],file:`src/data/${name}.json`,fields:Object.entries(JSON.parse(readFileSync(`src/data/${name}.json`))).map(([k,v])=>k==='body'?{name:k,label:'Informativa',widget:'markdown'}:field(k,v))}));
const string=(name,label)=>({name,label,widget:'string'});const common=[string('title','Titolo'),{name:'date',label:'Data',widget:'datetime',date_format:'DD/MM/YYYY',time_format:false,format:'YYYY-MM-DD'},{name:'draft',label:'Bozza (disattiva per pubblicare)',widget:'boolean',default:true}];
const media=(name,label,kind)=>({name,label,widget:'r2-file',kind,required:false});
const folder=(name,label,fields)=>({name,label,folder:`src/content/${name}`,create:true,extension:'json',format:'json',slug:'{{year}}-{{month}}-{{day}}-{{slug}}',summary:'{{title}}',fields:[...common,...fields]});
const config={backend:{name:'github',repo:'accademiamusicalevivaldi/accademia-musicale-vivaldi',branch:'main',base_url:'https://www.accademiamusicalevivaldi.com',auth_endpoint:'api/auth'},locale:'it',site_url:'https://www.accademiamusicalevivaldi.com',display_url:'https://www.accademiamusicalevivaldi.com',media_folder:'public/uploads',public_folder:'/uploads',collections:[{name:'settings',label:'Impostazioni del sito',files:settings},folder('notizie','Notizie',[{name:'excerpt',label:'Riassunto',widget:'text'},media('cover','Copertina','image'),{...string('coverAlt','Descrizione copertina'),required:false},{name:'body',label:'Testo',widget:'markdown'}]),folder('gallerie','Gallerie',[string('location','Località'),{name:'description',label:'Descrizione',widget:'text'},media('cover','Copertina','image'),{name:'photos',label:'Fotografie',widget:'list',summary:'{{fields.alt}}',fields:[{...media('url','Foto','image'),required:true},string('alt','Descrizione della foto')]}]),folder('documenti','Materiale didattico',[string('category','Categoria'),{name:'description',label:'Descrizione',widget:'text'},{...media('file','Documento PDF','pdf'),required:true}])]};
writeFileSync('public/admin/config.json',JSON.stringify(config,null,2)+'\n');
